"""empty message

Revision ID: fe9ec652b644
Revises: 
Create Date: 2022-03-30 06:57:15.934802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9ec652b644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('products', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('current_shopping_list_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('users_shopping_list',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_name', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shopping_list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_shopping_list')
    op.drop_table('users')
    op.drop_table('shopping_list')
    # ### end Alembic commands ###
